# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UNIGUI120.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1053, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroung_whole = QtWidgets.QLabel(self.centralwidget)
        self.backgroung_whole.setGeometry(QtCore.QRect(-90, -70, 2000, 1050))
        self.backgroung_whole.setAutoFillBackground(False)
        self.backgroung_whole.setStyleSheet("font: 20pt \"Segoe UI Emoji\";\n"
"background-color: rgb(0, 0, 127);\n"
"color: rgb(0, 0, 255);")
        self.backgroung_whole.setText("")
        self.backgroung_whole.setPixmap(QtGui.QPixmap("GUI/1129018.jpg"))
        self.backgroung_whole.setScaledContents(True)
        self.backgroung_whole.setObjectName("backgroung_whole")
        self.GUI_1 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_1.setGeometry(QtCore.QRect(5, 380, 375, 300))
        self.GUI_1.setStyleSheet("background-color: rgb(85, 240, 255);\n"
"color: rgb(0, 0, 255);")
        self.GUI_1.setText("")
        self.GUI_1.setPixmap(QtGui.QPixmap("GUI/download.gif"))
        self.GUI_1.setScaledContents(True)
        self.GUI_1.setObjectName("GUI_1")

        self.GUI_2 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_2.setGeometry(QtCore.QRect(1, 700, 380, 270))
        self.GUI_2.setText("")
        self.GUI_2.setPixmap(QtGui.QPixmap("GUI/Jarvis_Gui (1).gif"))
        self.GUI_2.setScaledContents(True)
        self.GUI_2.setObjectName("GUI_2")

        self.GUI_3 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_3.setGeometry(QtCore.QRect(1510, 25, 380, 300))
        self.GUI_3.setText("")
        self.GUI_3.setPixmap(QtGui.QPixmap("GUI/Earth.gif"))
        self.GUI_3.setScaledContents(True)
        self.GUI_3.setObjectName("GUI_3")

        self.GUI_4 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_4.setGeometry(QtCore.QRect(2, 25, 380, 300))
        self.GUI_4.setText("")
        self.GUI_4.setPixmap(QtGui.QPixmap("GUI/2fe4f743123363998082c968ca1130c8_w200.gif"))
        self.GUI_4.setScaledContents(True)
        self.GUI_4.setObjectName("GUI_4")

        self.GUI_5 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_5.setGeometry(QtCore.QRect(500, 160, 850, 550))
        self.GUI_5.setText("")
        self.GUI_5.setPixmap(QtGui.QPixmap("GUI/iron.gif"))
        self.GUI_5.setScaledContents(True)
        self.GUI_5.setObjectName("GUI_5")

        self.GUI_6 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_6.setGeometry(QtCore.QRect(550, 710, 800, 300))
        self.GUI_6.setText("")
        self.GUI_6.setPixmap(QtGui.QPixmap("GUI/loading.gif"))
        self.GUI_6.setScaledContents(True)
        self.GUI_6.setObjectName("GUI_6")

        self.GUI_7 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_7.setGeometry(QtCore.QRect(1510, 360, 380, 300))
        self.GUI_7.setText("")
        self.GUI_7.setPixmap(QtGui.QPixmap("GUI/57fa9d62d1a1b9fb4be02c2518738508.gif"))
        self.GUI_7.setScaledContents(True)
        self.GUI_7.setObjectName("GUI_7")

        self.GUI_8 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_8.setGeometry(QtCore.QRect(1510, 700, 380, 270))
        self.GUI_8.setText("")
        self.GUI_8.setPixmap(QtGui.QPixmap("GUI/y80EW4.gif"))
        self.GUI_8.setScaledContents(True)
        self.GUI_8.setObjectName("GUI_8")



        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(400, 830, 140, 80))
        self.pushButton_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/Start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1.setIcon(icon)
        self.pushButton_1.setIconSize(QtCore.QSize(200, 120))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1360, 810, 130, 100))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/Quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(290, 120))
        self.pushButton_2.setObjectName("pushButton_2")
        self.TIME = QtWidgets.QLabel(self.centralwidget)
        self.TIME.setGeometry(QtCore.QRect(1040, 25, 300, 120))
        self.TIME.setText("")
        self.TIME.setPixmap(QtGui.QPixmap("GUI/download.jpeg"))
        self.TIME.setScaledContents(True)
        self.TIME.setObjectName("TIME")



        self.NAME_1 = QtWidgets.QLabel(self.centralwidget)
        self.NAME_1.setGeometry(QtCore.QRect(330, 510, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.NAME_1.setFont(font)
        self.NAME_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.NAME_1.setPixmap(QtGui.QPixmap("GUI/download.jpeg"))
        self.NAME_1.setScaledContents(True)
        self.NAME_1.setObjectName("NAME_1")
        self.WEATHER = QtWidgets.QLabel(self.centralwidget)
        self.WEATHER.setGeometry(QtCore.QRect(550, 25, 300, 120))
        self.WEATHER.setText("")
        self.WEATHER.setPixmap(QtGui.QPixmap("GUI/download.jpeg"))
        self.WEATHER.setScaledContents(True)
        self.WEATHER.setObjectName("WEATHER")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NAME_1.setText(_translate("MainWindow", "                     UNICORN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
